version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mialeds
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: mialeds
      MYSQL_ROOT_PASSWORD: nacional2000
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mialeds-net

  app:
    build: .
    container_name: mialeds-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mialeds?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nacional2000
    networks:
      - mialeds-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mialeds-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - mialeds-net

volumes:
  mysql_data:

networks:
  mialeds-net:
